blank_issues_enabled: true
contact_links:
  - name: Discussions
    url: https://github.com/priyal2307/demand-forecast-explainer/discussions
    about: Have a question? Start a discussion instead of an issue
  - name: Contributing Guide
    url: https://github.com/priyal2307/demand-forecast-explainer/blob/main/CONTRIBUTING.md
    about: Learn how to contribute to this project
